baseurl = "https://blog.asharpminor.com/"
languageCode = "ja"
title = "a sharp minor"
HasCJKLanguage = true
SectionPagesMenu = "sections"
Paginate = 20
ignoreFiles = [ "\\*~$" ]
summaryLength = 140

[params]
Description = "Every word is like an unnecessary stain on silence and nothingness"
Author = "Shinichi SUGIYAMA"
DateForm = "2006年1月2日"
GoogleAnalyticsUserID =	"UA-7045949-1"
Twitter = "chez_sugi"
Github = "ssugiyama"
ShowRelatedPost = 1

[[menu.header]]
	name = "このサイトについて"
	weight = -100
	identifier = "about"
	url = "/about"

[[menu.header]]
	name = "よりぬきツイート"
	weight = -90
	identifier = "tweets"
	url = "/tweets"

[[menu.header]]
	name = "プレイリスト"
	weight = -80
	identifier = "playlists"
	url = "/playlists"

[[menu.header]]
	name = "walklog"
	weight = -70
	identifier = "walklog"
	url = "https://walk.asharpminor.com"

 [[menu.sections]]
        name = "演劇ノート"
        weight = -100
        identifier = "play"
        url = "/play/"
 [[menu.sections]]
        name = "読書ノート"
        weight = -90
        identifier = "book"
        url = "/book/"
 [[menu.sections]]
        name = "翻訳ラボ"
        weight = -80
        identifier = "translation"
        url = "/translation/"
 [[menu.sections]]
        name = "SAQ"
        weight = -70
        identifier = "saq"
        url = "/saq/"
 [[menu.sections]]
        name = "ふらんせ入門"
        weight = -60
        identifier = "francais"
        url = "/francais/"
 [[menu.sections]]
        name = "lost+found"
        weight = -50
        identifier = "lost+found"
        url = "/lost+found/"

[markup.goldmark.renderer]
  unsafe = true